CICD_TYPE ?= kind

kubectl ?= $(BIN_PATH)/kubectl

cicd/start: ## Start CICD kubernetes cluster
	$(MAKE) $(CICD_TYPE)/start/cluster

cicd/stop: ## Stop CICD kubernetes cluster
	$(MAKE) $(CICD_TYPE)/stop/cluster

cicd/dnsforward/start: $(CICD_TYPE)/dnsforward/start ## Forwards all dns requests to dns-proxy-server
	@echo ''
	@echo "Web UI: http://localhost:5380"
	@echo "To Stop: make cicd/dnsforward/stop"

cicd/dnsforward/stop: ## Stops dns forwarding
	$(docker) stop dns-proxy-server || true